# List Functions (1:10:46)
lucky_numbers = [42, 4, 8, 15, 16, 23, 2]
friends = ["Kevin", "Karen", "Mike", "Jim", "Oscar"]
friends2 = ["Kevin", "Karen", "Mike", "Jim", "Oscar"]

print(friends)
friends2.extend(lucky_numbers)
print(friends2)
friends.append("Sabuesito")
print(friends)
friends.insert(2, "Cat")
print(friends)
friends.remove("Cat")
print(friends)
friends2.clear()
print(friends2)
friends.pop()
print(friends)
print(friends.index("Karen"))
friends.append("Mike")
print(friends.count("Mike"))
friends.sort()
print(friends)
lucky_numbers.sort()
print(lucky_numbers)
lucky_numbers.reverse()
print(lucky_numbers)
friends2 = friends.copy()
print(friends2)